export const FETCH_BIZ_SUCCESS = 'FETCH_BIZ_SUCCESS'
export const FETCH_BIZ_FAIL = 'FETCH_BIZ_FAIL'
export const FIND_BIZ_SUCCESS = 'FIND_BIZ_SUCCESS'
export const FIND_BIZ_FAIL = 'FIND_BIZ_FAIL'

export const FETCH_CURRENTBIZMENU_SUCCESS = 'FETCH_CURRENTBIZMENU_SUCCESS'
export const FETCH_CURRENTBIZMENU_FAIL = 'FETCH_CURRENTBIZMENU_FAIL'