export const FETCH_BIZ_SUCCESS = 'FETCH_BIZ_SUCCESS'
export const FETCH_BIZ_FAIL = 'FETCH_BIZ_FAIL'
export const FIND_BIZ_SUCCESS = 'FIND_BIZ_SUCCESS'
export const FIND_BIZ_FAIL = 'FIND_BIZ_FAIL'

export const FETCH_CURRENTBIZMENU_SUCCESS = 'FETCH_CURRENTBIZMENU_SUCCESS'
export const FETCH_CURRENTBIZMENU_FAIL = 'FETCH_CURRENTBIZMENU_FAIL'

export const SET_BIZ_SUCCESS = 'SET_BIZ_SUCCESS'
export const SET_BIZ_FAIL = 'SET_BIZ_FAIL'

export const SET_ORDER_DATE_SUCCESS = 'SET_ORDER_DATE_SUCCESS'
export const SET_ORDER_DATE_FAIL = 'SET_ORDER_DATE_FAIL'

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS'
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL'

export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS'
export const REMOVE_ITEM_FROM_CART_FAIL = 'REMOVE_ITEM_FROM_CART_FAIL'